name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          registry-url: 'https://registry.npmjs.org'

      - name: Checks
        run: |
          set -xe
          npm ci --force
          # npm run checks:ci

      - name: Build
        run: |
          npm run build

      - name: Get Version
        id: version
        run: |
          set -xe
          tag=${{ github.event.release.tag_name }}
          version=${tag#"v"}
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Update package.json
        run: |
          set -xe
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.version.outputs.version }}\"/" package.json
          git config --local user.email "paul.savignano@gmail.com"
          git config --local user.name "PaulSavignano"
          git commit -am "ci: update package.json version to ${{ steps.version.outputs.version }}"
          git push origin main

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
